<?xml version="1.0" encoding="utf-8"?><Database Name="enap_v1" Class="DataClassesEnapDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ESTEBAN-HP\SQLEXPRESS;Initial Catalog=enap_v1;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="enap_v1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.E006_3" Member="E006_3">
    <Type Name="E006_3">
      <Column Name="ID_INFORME" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="E00_ID_INFORME" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_EVENTO_EMPRESA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHA_INGRESO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CLASIFICACION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="E006_3_E006_4" Member="E006_41" ThisKey="ID_INFORME" OtherKey="E00_ID_INFORME" Type="E006_4" />
      <Association Name="E006_3_HISTORIAL_INFORME" Member="HISTORIAL_INFORME" ThisKey="ID_INFORME" OtherKey="ID_INFORME" Type="HISTORIAL_INFORME" />
      <Association Name="E006_3_TBL_ACCION_CORRECTIVA" Member="TBL_ACCION_CORRECTIVA" ThisKey="ID_INFORME" OtherKey="ID_INFORME" Type="TBL_ACCION_CORRECTIVA" />
      <Association Name="E006_3_TBL_ARCHIVO" Member="TBL_ARCHIVO" ThisKey="ID_INFORME" OtherKey="ID_INFORME" Type="TBL_ARCHIVO" />
      <Association Name="E006_3_TBL_EVENTO_DATO" Member="TBL_EVENTO_DATO" ThisKey="ID_INFORME" OtherKey="ID_INFORME" Type="TBL_EVENTO_DATO" />
      <Association Name="E006_4_E006_3" Member="E006_4" ThisKey="E00_ID_INFORME" OtherKey="ID_INFORME" Type="E006_4" IsForeignKey="true" />
      <Association Name="TBL_EVENTO_EMPRESA_E006_3" Member="TBL_EVENTO_EMPRESA" ThisKey="ID_EVENTO_EMPRESA" OtherKey="ID_EVENTO_EMPRESA" Type="TBL_EVENTO_EMPRESA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_USUARIO_GRUPO" Member="TBL_USUARIO_GRUPO">
    <Type Name="TBL_USUARIO_GRUPO">
      <Column Name="ID_USUARIO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_GRUPO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GRUPO_ADMIN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TBL_GRUPO_TBL_USUARIO_GRUPO" Member="TBL_GRUPO" ThisKey="ID_GRUPO" OtherKey="ID_GRUPO" Type="TBL_GRUPO" IsForeignKey="true" />
      <Association Name="TBL_USUARIO_TBL_USUARIO_GRUPO" Member="TBL_USUARIO" ThisKey="ID_USUARIO" OtherKey="ID_USUARIO" Type="TBL_USUARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.E006_4" Member="E006_4">
    <Type Name="E006_4">
      <Column Name="ID_INFORME" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="E00_ID_INFORME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DESCRIPCION_INCIDENTE" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ANTECEDENTES" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RELATO_DE_HECHO" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="COMENTARIO" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FECHA_CREACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="E006_4_E006_3" Member="E006_3" ThisKey="ID_INFORME" OtherKey="E00_ID_INFORME" Type="E006_3" />
      <Association Name="E006_4_TBL_CAUSA" Member="TBL_CAUSA" ThisKey="ID_INFORME" OtherKey="ID_INFORME" Type="TBL_CAUSA" />
      <Association Name="E006_3_E006_4" Member="E006_31" ThisKey="E00_ID_INFORME" OtherKey="ID_INFORME" Type="E006_3" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HISTORIAL_INFORME" Member="HISTORIAL_INFORME">
    <Type Name="HISTORIAL_INFORME">
      <Column Name="ID_HISTORIAL_INFORME" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_INFORME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHA_MODIFICACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DESCRIPCION_MODIFICACION" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="E006_3_HISTORIAL_INFORME" Member="E006_3" ThisKey="ID_INFORME" OtherKey="ID_INFORME" Type="E006_3" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MATRIZ_EMPRESA" Member="MATRIZ_EMPRESA">
    <Type Name="MATRIZ_EMPRESA">
      <Column Name="ID_MATRIZ" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_EMPRESA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FECHA_CREACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TBL_EMPRESA_MATRIZ_EMPRESA" Member="TBL_EMPRESA" ThisKey="ID_EMPRESA" OtherKey="ID_EMPRESA" Type="TBL_EMPRESA" IsForeignKey="true" />
      <Association Name="TBL_MATRIZ_MATRIZ_EMPRESA" Member="TBL_MATRIZ" ThisKey="ID_MATRIZ" OtherKey="ID_MATRIZ" Type="TBL_MATRIZ" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MATRIZ_HISTORIAL" Member="MATRIZ_HISTORIAL">
    <Type Name="MATRIZ_HISTORIAL">
      <Column Name="ID_MATRIZ_HISTORIAL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_MATRIZ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHA_ACTUALIZACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DESCRIPCION_ACTUALIZACION" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="TBL_MATRIZ_MATRIZ_HISTORIAL" Member="TBL_MATRIZ" ThisKey="ID_MATRIZ" OtherKey="ID_MATRIZ" Type="TBL_MATRIZ" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_ACCION" Member="TBL_ACCION">
    <Type Name="TBL_ACCION">
      <Column Name="ID_ACCION" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE_ACCION" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="TBL_ACCION_TBL_ACCION_CORRECTIVA" Member="TBL_ACCION_CORRECTIVA" ThisKey="ID_ACCION" OtherKey="ID_ACCION" Type="TBL_ACCION_CORRECTIVA" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_ACCION_CORRECTIVA" Member="TBL_ACCION_CORRECTIVA">
    <Type Name="TBL_ACCION_CORRECTIVA">
      <Column Name="ID_ACCION_CORRECTIVA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_USUARIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_INFORME" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_ACCION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHA_PLAZO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FECHA_REALIZACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PORCENTAJE_CUMPLIMIENTO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FECHA_CREACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TBL_ACCION_CORRECTIVA_TBL_ACCION_CORRECTIVA_RECURSO" Member="TBL_ACCION_CORRECTIVA_RECURSO" ThisKey="ID_ACCION_CORRECTIVA" OtherKey="ID_ACCION_CORRECTIVA" Type="TBL_ACCION_CORRECTIVA_RECURSO" />
      <Association Name="E006_3_TBL_ACCION_CORRECTIVA" Member="E006_3" ThisKey="ID_INFORME" OtherKey="ID_INFORME" Type="E006_3" IsForeignKey="true" />
      <Association Name="TBL_ACCION_TBL_ACCION_CORRECTIVA" Member="TBL_ACCION" ThisKey="ID_ACCION" OtherKey="ID_ACCION" Type="TBL_ACCION" IsForeignKey="true" />
      <Association Name="TBL_USUARIO_TBL_ACCION_CORRECTIVA" Member="TBL_USUARIO" ThisKey="ID_USUARIO" OtherKey="ID_USUARIO" Type="TBL_USUARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_ACCION_CORRECTIVA_RECURSO" Member="TBL_ACCION_CORRECTIVA_RECURSO">
    <Type Name="TBL_ACCION_CORRECTIVA_RECURSO">
      <Column Name="ID_RECURSO_COMPROMETIDO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_ACCION_CORRECTIVA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UTILIZADO" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TBL_ACCION_CORRECTIVA_TBL_ACCION_CORRECTIVA_RECURSO" Member="TBL_ACCION_CORRECTIVA" ThisKey="ID_ACCION_CORRECTIVA" OtherKey="ID_ACCION_CORRECTIVA" Type="TBL_ACCION_CORRECTIVA" IsForeignKey="true" />
      <Association Name="TBL_RECURSO_COMPROMETIDO_TBL_ACCION_CORRECTIVA_RECURSO" Member="TBL_RECURSO_COMPROMETIDO" ThisKey="ID_RECURSO_COMPROMETIDO" OtherKey="ID_RECURSO_COMPROMETIDO" Type="TBL_RECURSO_COMPROMETIDO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_ACTIVIDAD_ESPECIFICA" Member="TBL_ACTIVIDAD_ESPECIFICA">
    <Type Name="TBL_ACTIVIDAD_ESPECIFICA">
      <Column Name="ID_ACTIVIDAD_ESPECIFICA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOM_ACTIVIDAD_ESPECIFICA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="TBL_ACTIVIDAD_ESPECIFICA_TBL_ACTIVIDAD_EVALUADA" Member="TBL_ACTIVIDAD_EVALUADA" ThisKey="ID_ACTIVIDAD_ESPECIFICA" OtherKey="ID_ACTIVIDAD_ESPECIFICA" Type="TBL_ACTIVIDAD_EVALUADA" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_ACTIVIDAD_EVALUADA" Member="TBL_ACTIVIDAD_EVALUADA">
    <Type Name="TBL_ACTIVIDAD_EVALUADA">
      <Column Name="ID_ACTIVIDAD_EVALUADA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_ACTIVIDAD_GENERAL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_CARGO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_DIVISION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_ACTIVIDAD_ESPECIFICA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_DEPARTAMENTO_ORGANIZACION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_PELIGRO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_AREA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VALORACION_CONSECUENCIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VALORACION_PROBABILIDAD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MEDIDA_VALORACION_CONSECUENCIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MEDIDA_VALORACION_PROBABILIDAD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHA_CREACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONDICION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_ACTIVIDAD_EVALUADA_TBL_MATRIZ_ACTIVIDAD" Member="TBL_MATRIZ_ACTIVIDAD" ThisKey="ID_ACTIVIDAD_EVALUADA" OtherKey="ID_ACTIVIDAD_EVALUADA" Type="TBL_MATRIZ_ACTIVIDAD" />
      <Association Name="TBL_ACTIVIDAD_EVALUADA_TBL_PELIGRO_MEDIDA" Member="TBL_PELIGRO_MEDIDA" ThisKey="ID_ACTIVIDAD_EVALUADA" OtherKey="ID_ACTIVIDAD_EVALUADA" Type="TBL_PELIGRO_MEDIDA" />
      <Association Name="TBL_ACTIVIDAD_ESPECIFICA_TBL_ACTIVIDAD_EVALUADA" Member="TBL_ACTIVIDAD_ESPECIFICA" ThisKey="ID_ACTIVIDAD_ESPECIFICA" OtherKey="ID_ACTIVIDAD_ESPECIFICA" Type="TBL_ACTIVIDAD_ESPECIFICA" IsForeignKey="true" />
      <Association Name="TBL_ACTIVIDAD_GENERAL_TBL_ACTIVIDAD_EVALUADA" Member="TBL_ACTIVIDAD_GENERAL" ThisKey="ID_ACTIVIDAD_GENERAL" OtherKey="ID_ACTIVIDAD_GENERAL" Type="TBL_ACTIVIDAD_GENERAL" IsForeignKey="true" />
      <Association Name="TBL_AREA_TBL_ACTIVIDAD_EVALUADA" Member="TBL_AREA" ThisKey="ID_AREA" OtherKey="ID_AREA" Type="TBL_AREA" IsForeignKey="true" />
      <Association Name="TBL_CARGO_TBL_ACTIVIDAD_EVALUADA" Member="TBL_CARGO" ThisKey="ID_CARGO" OtherKey="ID_CARGO" Type="TBL_CARGO" IsForeignKey="true" />
      <Association Name="TBL_DEPARTAMENTO_ORGANIZACION_TBL_ACTIVIDAD_EVALUADA" Member="TBL_DEPARTAMENTO_ORGANIZACION" ThisKey="ID_DEPARTAMENTO_ORGANIZACION" OtherKey="ID_DEPARTAMENTO_ORGANIZACION" Type="TBL_DEPARTAMENTO_ORGANIZACION" IsForeignKey="true" />
      <Association Name="TBL_DIVISION_TBL_ACTIVIDAD_EVALUADA" Member="TBL_DIVISION" ThisKey="ID_DIVISION" OtherKey="ID_DIVISION" Type="TBL_DIVISION" IsForeignKey="true" />
      <Association Name="TBL_PELIGRO_TBL_ACTIVIDAD_EVALUADA" Member="TBL_PELIGRO" ThisKey="ID_PELIGRO" OtherKey="ID_PELIGRO" Type="TBL_PELIGRO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_ACTIVIDAD_GENERAL" Member="TBL_ACTIVIDAD_GENERAL">
    <Type Name="TBL_ACTIVIDAD_GENERAL">
      <Column Name="ID_ACTIVIDAD_GENERAL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOM_ACTIVIDAD_GENERAL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="TBL_ACTIVIDAD_GENERAL_TBL_ACTIVIDAD_EVALUADA" Member="TBL_ACTIVIDAD_EVALUADA" ThisKey="ID_ACTIVIDAD_GENERAL" OtherKey="ID_ACTIVIDAD_GENERAL" Type="TBL_ACTIVIDAD_EVALUADA" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_ACTIVIDAD_RESPONSABLE" Member="TBL_ACTIVIDAD_RESPONSABLE">
    <Type Name="TBL_ACTIVIDAD_RESPONSABLE">
      <Column Name="ID_SUB_ACTIVIDAD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_CARGO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="TBL_CARGO_TBL_ACTIVIDAD_RESPONSABLE" Member="TBL_CARGO" ThisKey="ID_CARGO" OtherKey="ID_CARGO" Type="TBL_CARGO" IsForeignKey="true" />
      <Association Name="TBL_SUB_ACTIVIDAD_TBL_ACTIVIDAD_RESPONSABLE" Member="TBL_SUB_ACTIVIDAD" ThisKey="ID_SUB_ACTIVIDAD" OtherKey="ID_SUB_ACTIVIDAD" Type="TBL_SUB_ACTIVIDAD" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_ACTIVIDAD_TRABAJADOR" Member="TBL_ACTIVIDAD_TRABAJADOR">
    <Type Name="TBL_ACTIVIDAD_TRABAJADOR">
      <Column Name="ID_ACTIVIDAD_TRABAJADOR" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE_ACTIVIDAD_TRABAJADOR" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="TBL_ACTIVIDAD_TRABAJADOR_TBL_ACTIVIDAD_TRABAJADOR_REALIZADA" Member="TBL_ACTIVIDAD_TRABAJADOR_REALIZADA" ThisKey="ID_ACTIVIDAD_TRABAJADOR" OtherKey="ID_ACTIVIDAD_TRABAJADOR" Type="TBL_ACTIVIDAD_TRABAJADOR_REALIZADA" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_ACTIVIDAD_TRABAJADOR_REALIZADA" Member="TBL_ACTIVIDAD_TRABAJADOR_REALIZADA">
    <Type Name="TBL_ACTIVIDAD_TRABAJADOR_REALIZADA">
      <Column Name="ID_TRABAJADOR" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_ACTIVIDAD_TRABAJADOR" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="REALIZADA" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TBL_ACTIVIDAD_TRABAJADOR_TBL_ACTIVIDAD_TRABAJADOR_REALIZADA" Member="TBL_ACTIVIDAD_TRABAJADOR" ThisKey="ID_ACTIVIDAD_TRABAJADOR" OtherKey="ID_ACTIVIDAD_TRABAJADOR" Type="TBL_ACTIVIDAD_TRABAJADOR" IsForeignKey="true" />
      <Association Name="TBL_TRABAJADOR_TBL_ACTIVIDAD_TRABAJADOR_REALIZADA" Member="TBL_TRABAJADOR" ThisKey="ID_TRABAJADOR" OtherKey="ID_TRABAJADOR" Type="TBL_TRABAJADOR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_ARCHIVO" Member="TBL_ARCHIVO">
    <Type Name="TBL_ARCHIVO">
      <Column Name="ID_ARCHIVO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_INFORME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NOMBRE_ARCHIVO" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PATH" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="E006_3_TBL_ARCHIVO" Member="E006_3" ThisKey="ID_INFORME" OtherKey="ID_INFORME" Type="E006_3" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_AREA" Member="TBL_AREA">
    <Type Name="TBL_AREA">
      <Column Name="ID_AREA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_DIVISION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NOMBRE_AREA" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="TBL_AREA_TBL_ACTIVIDAD_EVALUADA" Member="TBL_ACTIVIDAD_EVALUADA" ThisKey="ID_AREA" OtherKey="ID_AREA" Type="TBL_ACTIVIDAD_EVALUADA" />
      <Association Name="TBL_DIVISION_TBL_AREA" Member="TBL_DIVISION" ThisKey="ID_DIVISION" OtherKey="ID_DIVISION" Type="TBL_DIVISION" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_CARGO" Member="TBL_CARGO">
    <Type Name="TBL_CARGO">
      <Column Name="ID_CARGO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE_CARGO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="TBL_CARGO_TBL_ACTIVIDAD_EVALUADA" Member="TBL_ACTIVIDAD_EVALUADA" ThisKey="ID_CARGO" OtherKey="ID_CARGO" Type="TBL_ACTIVIDAD_EVALUADA" />
      <Association Name="TBL_CARGO_TBL_ACTIVIDAD_RESPONSABLE" Member="TBL_ACTIVIDAD_RESPONSABLE" ThisKey="ID_CARGO" OtherKey="ID_CARGO" Type="TBL_ACTIVIDAD_RESPONSABLE" />
      <Association Name="TBL_CARGO_TBL_TRABAJADOR" Member="TBL_TRABAJADOR" ThisKey="ID_CARGO" OtherKey="ID_CARGO" Type="TBL_TRABAJADOR" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_CAUSA" Member="TBL_CAUSA">
    <Type Name="TBL_CAUSA">
      <Column Name="ID_CAUSA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_INFORME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TIPO_CAUSA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_CAUSA_TBL_CAUSA_MEDIDA_DE_CONTROL" Member="TBL_CAUSA_MEDIDA_DE_CONTROL" ThisKey="ID_CAUSA" OtherKey="ID_CAUSA" Type="TBL_CAUSA_MEDIDA_DE_CONTROL" />
      <Association Name="E006_4_TBL_CAUSA" Member="E006_4" ThisKey="ID_INFORME" OtherKey="ID_INFORME" Type="E006_4" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_CAUSA_MEDIDA_DE_CONTROL" Member="TBL_CAUSA_MEDIDA_DE_CONTROL">
    <Type Name="TBL_CAUSA_MEDIDA_DE_CONTROL">
      <Column Name="ID_CAUSA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_MEDIDAS_DE_CONTROL" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TBL_CAUSA_TBL_CAUSA_MEDIDA_DE_CONTROL" Member="TBL_CAUSA" ThisKey="ID_CAUSA" OtherKey="ID_CAUSA" Type="TBL_CAUSA" IsForeignKey="true" />
      <Association Name="TBL_MEDIDA_DE_CONTROL_TBL_CAUSA_MEDIDA_DE_CONTROL" Member="TBL_MEDIDA_DE_CONTROL" ThisKey="ID_MEDIDAS_DE_CONTROL" OtherKey="ID_MEDIDAS_DE_CONTROL" Type="TBL_MEDIDA_DE_CONTROL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_CONSECUENCIA" Member="TBL_CONSECUENCIA">
    <Type Name="TBL_CONSECUENCIA">
      <Column Name="ID_CONSECUENCIA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PELIGRO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NOMBRE_CONSECUENCIA" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="TBL_PELIGRO_TBL_CONSECUENCIA" Member="TBL_PELIGRO" ThisKey="ID_PELIGRO" OtherKey="ID_PELIGRO" Type="TBL_PELIGRO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_DATO_EVENTO" Member="TBL_DATO_EVENTO">
    <Type Name="TBL_DATO_EVENTO">
      <Column Name="ID_TIPO_EVENTO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE_TIPO_EVENTO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TIPO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_DATO_EVENTO_TBL_EVENTO_DATO" Member="TBL_EVENTO_DATO" ThisKey="ID_TIPO_EVENTO" OtherKey="ID_TIPO_EVENTO" Type="TBL_EVENTO_DATO" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_DEPARTAMENTO" Member="TBL_DEPARTAMENTO">
    <Type Name="TBL_DEPARTAMENTO">
      <Column Name="ID_DEPARTAMENTO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE_DEPARTAMENTO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="TBL_DEPARTAMENTO_TBL_DEPARTAMENTO_ORGANIZACION" Member="TBL_DEPARTAMENTO_ORGANIZACION" ThisKey="ID_DEPARTAMENTO" OtherKey="ID_DEPARTAMENTO" Type="TBL_DEPARTAMENTO_ORGANIZACION" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_DEPARTAMENTO_ORGANIZACION" Member="TBL_DEPARTAMENTO_ORGANIZACION">
    <Type Name="TBL_DEPARTAMENTO_ORGANIZACION">
      <Column Name="ID_DEPARTAMENTO_ORGANIZACION" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_ORGANIZACION" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_DEPARTAMENTO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TBL_DEPARTAMENTO_ORGANIZACION_TBL_ACTIVIDAD_EVALUADA" Member="TBL_ACTIVIDAD_EVALUADA" ThisKey="ID_DEPARTAMENTO_ORGANIZACION" OtherKey="ID_DEPARTAMENTO_ORGANIZACION" Type="TBL_ACTIVIDAD_EVALUADA" />
      <Association Name="TBL_DEPARTAMENTO_ORGANIZACION_TBL_DIVISION" Member="TBL_DIVISION" ThisKey="ID_DEPARTAMENTO_ORGANIZACION" OtherKey="ID_DEPARTAMENTO_ORGANIZACION" Type="TBL_DIVISION" />
      <Association Name="TBL_DEPARTAMENTO_ORGANIZACION_TBL_EVENTO" Member="TBL_EVENTO" ThisKey="ID_DEPARTAMENTO_ORGANIZACION" OtherKey="ID_DEPARTAMENTO_ORGANIZACION" Type="TBL_EVENTO" />
      <Association Name="TBL_DEPARTAMENTO_ORGANIZACION_TBL_PUNTO_GEOGRAFICO" Member="TBL_PUNTO_GEOGRAFICO" ThisKey="ID_DEPARTAMENTO_ORGANIZACION" OtherKey="ID_DEPARTAMENTO_ORGANIZACION" Type="TBL_PUNTO_GEOGRAFICO" />
      <Association Name="TBL_DEPARTAMENTO_TBL_DEPARTAMENTO_ORGANIZACION" Member="TBL_DEPARTAMENTO" ThisKey="ID_DEPARTAMENTO" OtherKey="ID_DEPARTAMENTO" Type="TBL_DEPARTAMENTO" IsForeignKey="true" />
      <Association Name="TBL_ORGANIZACION_TBL_DEPARTAMENTO_ORGANIZACION" Member="TBL_ORGANIZACION" ThisKey="ID_ORGANIZACION" OtherKey="ID_ORGANIZACION" Type="TBL_ORGANIZACION" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_DIVISION" Member="TBL_DIVISION">
    <Type Name="TBL_DIVISION">
      <Column Name="ID_DIVISION" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_DEPARTAMENTO_ORGANIZACION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NOMBRE_DIVISION" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="TBL_DIVISION_TBL_ACTIVIDAD_EVALUADA" Member="TBL_ACTIVIDAD_EVALUADA" ThisKey="ID_DIVISION" OtherKey="ID_DIVISION" Type="TBL_ACTIVIDAD_EVALUADA" />
      <Association Name="TBL_DIVISION_TBL_AREA" Member="TBL_AREA" ThisKey="ID_DIVISION" OtherKey="ID_DIVISION" Type="TBL_AREA" />
      <Association Name="TBL_DEPARTAMENTO_ORGANIZACION_TBL_DIVISION" Member="TBL_DEPARTAMENTO_ORGANIZACION" ThisKey="ID_DEPARTAMENTO_ORGANIZACION" OtherKey="ID_DEPARTAMENTO_ORGANIZACION" Type="TBL_DEPARTAMENTO_ORGANIZACION" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_EMPRESA" Member="TBL_EMPRESA">
    <Type Name="TBL_EMPRESA">
      <Column Name="ID_EMPRESA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE_EMPRESA" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="DIRECCION_EMPRESA" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="FONO_EMPRESA" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EMAIL_EMPRESA" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="NOMBRE_CONTRATO" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Association Name="TBL_EMPRESA_MATRIZ_EMPRESA" Member="MATRIZ_EMPRESA" ThisKey="ID_EMPRESA" OtherKey="ID_EMPRESA" Type="MATRIZ_EMPRESA" />
      <Association Name="TBL_EMPRESA_TBL_EVENTO_EMPRESA" Member="TBL_EVENTO_EMPRESA" ThisKey="ID_EMPRESA" OtherKey="ID_EMPRESA" Type="TBL_EVENTO_EMPRESA" />
      <Association Name="TBL_EMPRESA_TBL_HISTORIAL_EMPRESA" Member="TBL_HISTORIAL_EMPRESA" ThisKey="ID_EMPRESA" OtherKey="ID_EMPRESA" Type="TBL_HISTORIAL_EMPRESA" />
      <Association Name="TBL_EMPRESA_TBL_USUARIO" Member="TBL_USUARIO" ThisKey="ID_EMPRESA" OtherKey="ID_EMPRESA" Type="TBL_USUARIO" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_EVALUACION_MENSUAL" Member="TBL_EVALUACION_MENSUAL">
    <Type Name="TBL_EVALUACION_MENSUAL">
      <Column Name="ID_EVALUACION_MENSUAL" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_SUB_ACTIVIDAD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROGRAMADO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="REALIZADO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHA_EVALUACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TBL_SUB_ACTIVIDAD_TBL_EVALUACION_MENSUAL" Member="TBL_SUB_ACTIVIDAD" ThisKey="ID_SUB_ACTIVIDAD" OtherKey="ID_SUB_ACTIVIDAD" Type="TBL_SUB_ACTIVIDAD" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_EVENTO" Member="TBL_EVENTO">
    <Type Name="TBL_EVENTO">
      <Column Name="ID_EVENTO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_DEPARTAMENTO_ORGANIZACION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OCURRIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHA_HORA_EVENTO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FECHA_INGRESO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LAT_EVENTO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LNG_EVENTO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TIPO_EVENTO" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LUGAR_EXACTO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="TBL_EVENTO_TBL_EVENTO_EMPRESA" Member="TBL_EVENTO_EMPRESA" ThisKey="ID_EVENTO" OtherKey="ID_EVENTO" Type="TBL_EVENTO_EMPRESA" />
      <Association Name="TBL_DEPARTAMENTO_ORGANIZACION_TBL_EVENTO" Member="TBL_DEPARTAMENTO_ORGANIZACION" ThisKey="ID_DEPARTAMENTO_ORGANIZACION" OtherKey="ID_DEPARTAMENTO_ORGANIZACION" Type="TBL_DEPARTAMENTO_ORGANIZACION" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_EVENTO_DATO" Member="TBL_EVENTO_DATO">
    <Type Name="TBL_EVENTO_DATO">
      <Column Name="ID_INFORME" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_TIPO_EVENTO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TBL_DATO_EVENTO_TBL_EVENTO_DATO" Member="TBL_DATO_EVENTO" ThisKey="ID_TIPO_EVENTO" OtherKey="ID_TIPO_EVENTO" Type="TBL_DATO_EVENTO" IsForeignKey="true" />
      <Association Name="E006_3_TBL_EVENTO_DATO" Member="E006_3" ThisKey="ID_INFORME" OtherKey="ID_INFORME" Type="E006_3" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_EVENTO_EMPRESA" Member="TBL_EVENTO_EMPRESA">
    <Type Name="TBL_EVENTO_EMPRESA">
      <Column Name="ID_EVENTO_EMPRESA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_EVENTO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_EMPRESA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TBL_EVENTO_EMPRESA_E006_3" Member="E006_3" ThisKey="ID_EVENTO_EMPRESA" OtherKey="ID_EVENTO_EMPRESA" Type="E006_3" />
      <Association Name="TBL_EVENTO_EMPRESA_TBL_EVENTO_TRABAJADOR" Member="TBL_EVENTO_TRABAJADOR" ThisKey="ID_EVENTO_EMPRESA" OtherKey="ID_EVENTO_EMPRESA" Type="TBL_EVENTO_TRABAJADOR" />
      <Association Name="TBL_EVENTO_TBL_EVENTO_EMPRESA" Member="TBL_EVENTO" ThisKey="ID_EVENTO" OtherKey="ID_EVENTO" Type="TBL_EVENTO" IsForeignKey="true" />
      <Association Name="TBL_EMPRESA_TBL_EVENTO_EMPRESA" Member="TBL_EMPRESA" ThisKey="ID_EMPRESA" OtherKey="ID_EMPRESA" Type="TBL_EMPRESA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_EVENTO_TRABAJADOR" Member="TBL_EVENTO_TRABAJADOR">
    <Type Name="TBL_EVENTO_TRABAJADOR">
      <Column Name="ID_EVENTO_TRABAJADOR" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_EVENTO_EMPRESA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TRABAJADOR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_MATRIZ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHA_PRESENTACION_HOSPITAL" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FECHA_ALTA_MEDICA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TIPO_LESION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_EVENTO_TRABAJADOR_TBL_PARTE_CORPORAL_TRABAJADOR" Member="TBL_PARTE_CORPORAL_TRABAJADOR" ThisKey="ID_EVENTO_TRABAJADOR" OtherKey="ID_EVENTO_TRABAJADOR" Type="TBL_PARTE_CORPORAL_TRABAJADOR" />
      <Association Name="TBL_EVENTO_EMPRESA_TBL_EVENTO_TRABAJADOR" Member="TBL_EVENTO_EMPRESA" ThisKey="ID_EVENTO_EMPRESA" OtherKey="ID_EVENTO_EMPRESA" Type="TBL_EVENTO_EMPRESA" IsForeignKey="true" />
      <Association Name="TBL_MATRIZ_TBL_EVENTO_TRABAJADOR" Member="TBL_MATRIZ" ThisKey="ID_MATRIZ" OtherKey="ID_MATRIZ" Type="TBL_MATRIZ" IsForeignKey="true" />
      <Association Name="TBL_TRABAJADOR_TBL_EVENTO_TRABAJADOR" Member="TBL_TRABAJADOR" ThisKey="ID_TRABAJADOR" OtherKey="ID_TRABAJADOR" Type="TBL_TRABAJADOR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_EVIDENCIA" Member="TBL_EVIDENCIA">
    <Type Name="TBL_EVIDENCIA">
      <Column Name="ID_EVIDENCIA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE_EVIDENCIA" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="TBL_EVIDENCIA_TBL_SUB_ACTIVIDAD" Member="TBL_SUB_ACTIVIDAD" ThisKey="ID_EVIDENCIA" OtherKey="ID_EVIDENCIA" Type="TBL_SUB_ACTIVIDAD" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_GRUPO" Member="TBL_GRUPO">
    <Type Name="TBL_GRUPO">
      <Column Name="ID_GRUPO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE_GRUPO" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DESCRIPCION_GRUPO" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="TBL_GRUPO_TBL_USUARIO_GRUPO" Member="TBL_USUARIO_GRUPO" ThisKey="ID_GRUPO" OtherKey="ID_GRUPO" Type="TBL_USUARIO_GRUPO" />
      <Association Name="TBL_GRUPO_TBL_GRUPO_PRIVILEGIO" Member="TBL_GRUPO_PRIVILEGIO" ThisKey="ID_GRUPO" OtherKey="ID_GRUPO" Type="TBL_GRUPO_PRIVILEGIO" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_GRUPO_PRIVILEGIO" Member="TBL_GRUPO_PRIVILEGIO">
    <Type Name="TBL_GRUPO_PRIVILEGIO">
      <Column Name="ID_GRUPO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_PRIVILEGIO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_MODULO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TBL_GRUPO_TBL_GRUPO_PRIVILEGIO" Member="TBL_GRUPO" ThisKey="ID_GRUPO" OtherKey="ID_GRUPO" Type="TBL_GRUPO" IsForeignKey="true" />
      <Association Name="TBL_MODULO_TBL_GRUPO_PRIVILEGIO" Member="TBL_MODULO" ThisKey="ID_MODULO" OtherKey="ID_MODULO" Type="TBL_MODULO" IsForeignKey="true" />
      <Association Name="TBL_PRIVILEGIO_TBL_GRUPO_PRIVILEGIO" Member="TBL_PRIVILEGIO" ThisKey="ID_PRIVILEGIO" OtherKey="ID_PRIVILEGIO" Type="TBL_PRIVILEGIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_HISTORIAL_EMPRESA" Member="TBL_HISTORIAL_EMPRESA">
    <Type Name="TBL_HISTORIAL_EMPRESA">
      <Column Name="ID_HISTORIAL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_EMPRESA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHA_CREACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="N_TRABAJADORES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="H_TRABAJADAS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="H_SOBRETIEMPO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_EMPRESA_TBL_HISTORIAL_EMPRESA" Member="TBL_EMPRESA" ThisKey="ID_EMPRESA" OtherKey="ID_EMPRESA" Type="TBL_EMPRESA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_MATRIZ" Member="TBL_MATRIZ">
    <Type Name="TBL_MATRIZ">
      <Column Name="ID_MATRIZ" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_USUARIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHA_CREACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TBL_MATRIZ_MATRIZ_EMPRESA" Member="MATRIZ_EMPRESA" ThisKey="ID_MATRIZ" OtherKey="ID_MATRIZ" Type="MATRIZ_EMPRESA" />
      <Association Name="TBL_MATRIZ_MATRIZ_HISTORIAL" Member="MATRIZ_HISTORIAL" ThisKey="ID_MATRIZ" OtherKey="ID_MATRIZ" Type="MATRIZ_HISTORIAL" />
      <Association Name="TBL_MATRIZ_TBL_EVENTO_TRABAJADOR" Member="TBL_EVENTO_TRABAJADOR" ThisKey="ID_MATRIZ" OtherKey="ID_MATRIZ" Type="TBL_EVENTO_TRABAJADOR" />
      <Association Name="TBL_MATRIZ_TBL_MATRIZ_ACTIVIDAD" Member="TBL_MATRIZ_ACTIVIDAD" ThisKey="ID_MATRIZ" OtherKey="ID_MATRIZ" Type="TBL_MATRIZ_ACTIVIDAD" />
      <Association Name="TBL_USUARIO_TBL_MATRIZ" Member="TBL_USUARIO" ThisKey="ID_USUARIO" OtherKey="ID_USUARIO" Type="TBL_USUARIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_MATRIZ_ACTIVIDAD" Member="TBL_MATRIZ_ACTIVIDAD">
    <Type Name="TBL_MATRIZ_ACTIVIDAD">
      <Column Name="ID_MATRIZ" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_ACTIVIDAD_EVALUADA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FECHA_CREACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TBL_ACTIVIDAD_EVALUADA_TBL_MATRIZ_ACTIVIDAD" Member="TBL_ACTIVIDAD_EVALUADA" ThisKey="ID_ACTIVIDAD_EVALUADA" OtherKey="ID_ACTIVIDAD_EVALUADA" Type="TBL_ACTIVIDAD_EVALUADA" IsForeignKey="true" />
      <Association Name="TBL_MATRIZ_TBL_MATRIZ_ACTIVIDAD" Member="TBL_MATRIZ" ThisKey="ID_MATRIZ" OtherKey="ID_MATRIZ" Type="TBL_MATRIZ" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_MEDIDA_DE_CONTROL" Member="TBL_MEDIDA_DE_CONTROL">
    <Type Name="TBL_MEDIDA_DE_CONTROL">
      <Column Name="ID_MEDIDAS_DE_CONTROL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOM_MEDIDA_DE_CONTROL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TBL_MEDIDA_DE_CONTROL_TBL_CAUSA_MEDIDA_DE_CONTROL" Member="TBL_CAUSA_MEDIDA_DE_CONTROL" ThisKey="ID_MEDIDAS_DE_CONTROL" OtherKey="ID_MEDIDAS_DE_CONTROL" Type="TBL_CAUSA_MEDIDA_DE_CONTROL" />
      <Association Name="TBL_MEDIDA_DE_CONTROL_TBL_PELIGRO_MEDIDA" Member="TBL_PELIGRO_MEDIDA" ThisKey="ID_MEDIDAS_DE_CONTROL" OtherKey="ID_MEDIDAS_DE_CONTROL" Type="TBL_PELIGRO_MEDIDA" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_MODULO" Member="TBL_MODULO">
    <Type Name="TBL_MODULO">
      <Column Name="ID_MODULO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE_MODULO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DESCRIPCION_MODULO" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="URL_MODULO" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Association Name="TBL_MODULO_TBL_GRUPO_PRIVILEGIO" Member="TBL_GRUPO_PRIVILEGIO" ThisKey="ID_MODULO" OtherKey="ID_MODULO" Type="TBL_GRUPO_PRIVILEGIO" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_ORGANIZACION" Member="TBL_ORGANIZACION">
    <Type Name="TBL_ORGANIZACION">
      <Column Name="ID_ORGANIZACION" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE_ORGANIZACION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="TBL_ORGANIZACION_TBL_DEPARTAMENTO_ORGANIZACION" Member="TBL_DEPARTAMENTO_ORGANIZACION" ThisKey="ID_ORGANIZACION" OtherKey="ID_ORGANIZACION" Type="TBL_DEPARTAMENTO_ORGANIZACION" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PARTE_CORPORAL" Member="TBL_PARTE_CORPORAL">
    <Type Name="TBL_PARTE_CORPORAL">
      <Column Name="ID_PARTE_CORPORAL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE_PARTE_CORPORAL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="TBL_PARTE_CORPORAL_TBL_PARTE_CORPORAL_TRABAJADOR" Member="TBL_PARTE_CORPORAL_TRABAJADOR" ThisKey="ID_PARTE_CORPORAL" OtherKey="ID_PARTE_CORPORAL" Type="TBL_PARTE_CORPORAL_TRABAJADOR" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PARTE_CORPORAL_TRABAJADOR" Member="TBL_PARTE_CORPORAL_TRABAJADOR">
    <Type Name="TBL_PARTE_CORPORAL_TRABAJADOR">
      <Column Name="ID_PARTE_CORPORAL" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_EVENTO_TRABAJADOR" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="TBL_EVENTO_TRABAJADOR_TBL_PARTE_CORPORAL_TRABAJADOR" Member="TBL_EVENTO_TRABAJADOR" ThisKey="ID_EVENTO_TRABAJADOR" OtherKey="ID_EVENTO_TRABAJADOR" Type="TBL_EVENTO_TRABAJADOR" IsForeignKey="true" />
      <Association Name="TBL_PARTE_CORPORAL_TBL_PARTE_CORPORAL_TRABAJADOR" Member="TBL_PARTE_CORPORAL" ThisKey="ID_PARTE_CORPORAL" OtherKey="ID_PARTE_CORPORAL" Type="TBL_PARTE_CORPORAL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PELIGRO" Member="TBL_PELIGRO">
    <Type Name="TBL_PELIGRO">
      <Column Name="ID_PELIGRO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOM_PELIGRO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="TBL_PELIGRO_TBL_ACTIVIDAD_EVALUADA" Member="TBL_ACTIVIDAD_EVALUADA" ThisKey="ID_PELIGRO" OtherKey="ID_PELIGRO" Type="TBL_ACTIVIDAD_EVALUADA" />
      <Association Name="TBL_PELIGRO_TBL_CONSECUENCIA" Member="TBL_CONSECUENCIA" ThisKey="ID_PELIGRO" OtherKey="ID_PELIGRO" Type="TBL_CONSECUENCIA" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PELIGRO_MEDIDA" Member="TBL_PELIGRO_MEDIDA">
    <Type Name="TBL_PELIGRO_MEDIDA">
      <Column Name="ID_MEDIDAS_DE_CONTROL" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_ACTIVIDAD_EVALUADA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FECHA_CREACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TBL_ACTIVIDAD_EVALUADA_TBL_PELIGRO_MEDIDA" Member="TBL_ACTIVIDAD_EVALUADA" ThisKey="ID_ACTIVIDAD_EVALUADA" OtherKey="ID_ACTIVIDAD_EVALUADA" Type="TBL_ACTIVIDAD_EVALUADA" IsForeignKey="true" />
      <Association Name="TBL_MEDIDA_DE_CONTROL_TBL_PELIGRO_MEDIDA" Member="TBL_MEDIDA_DE_CONTROL" ThisKey="ID_MEDIDAS_DE_CONTROL" OtherKey="ID_MEDIDAS_DE_CONTROL" Type="TBL_MEDIDA_DE_CONTROL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PRIVILEGIO" Member="TBL_PRIVILEGIO">
    <Type Name="TBL_PRIVILEGIO">
      <Column Name="ID_PRIVILEGIO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE_PRIVILEGIO" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TBL_PRIVILEGIO_TBL_GRUPO_PRIVILEGIO" Member="TBL_GRUPO_PRIVILEGIO" ThisKey="ID_PRIVILEGIO" OtherKey="ID_PRIVILEGIO" Type="TBL_GRUPO_PRIVILEGIO" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PROGRAMA_ACTIVIDAD" Member="TBL_PROGRAMA_ACTIVIDAD">
    <Type Name="TBL_PROGRAMA_ACTIVIDAD">
      <Column Name="ID_PROGRAMA_ACTIVIDAD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PROGRAMA_ANUAL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NOMBRE_PROGRAMA_ACTIVIDAD" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="TBL_PROGRAMA_ACTIVIDAD_TBL_SUB_ACTIVIDAD" Member="TBL_SUB_ACTIVIDAD" ThisKey="ID_PROGRAMA_ACTIVIDAD" OtherKey="ID_PROGRAMA_ACTIVIDAD" Type="TBL_SUB_ACTIVIDAD" />
      <Association Name="TBL_PROGRAMA_ANUAL_TBL_PROGRAMA_ACTIVIDAD" Member="TBL_PROGRAMA_ANUAL" ThisKey="ID_PROGRAMA_ANUAL" OtherKey="ID_PROGRAMA_ANUAL" Type="TBL_PROGRAMA_ANUAL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PROGRAMA_ANUAL" Member="TBL_PROGRAMA_ANUAL">
    <Type Name="TBL_PROGRAMA_ANUAL">
      <Column Name="ID_PROGRAMA_ANUAL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OBJETIVO" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="META" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FECHA_CREACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="TBL_PROGRAMA_ANUAL_TBL_PROGRAMA_ACTIVIDAD" Member="TBL_PROGRAMA_ACTIVIDAD" ThisKey="ID_PROGRAMA_ANUAL" OtherKey="ID_PROGRAMA_ANUAL" Type="TBL_PROGRAMA_ACTIVIDAD" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_PUNTO_GEOGRAFICO" Member="TBL_PUNTO_GEOGRAFICO">
    <Type Name="TBL_PUNTO_GEOGRAFICO">
      <Column Name="ID_PUNTO_GEOGRAFICA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_DEPARTAMENTO_ORGANIZACION" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LAT_PUNTO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LNG_PUNTO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="TBL_DEPARTAMENTO_ORGANIZACION_TBL_PUNTO_GEOGRAFICO" Member="TBL_DEPARTAMENTO_ORGANIZACION" ThisKey="ID_DEPARTAMENTO_ORGANIZACION" OtherKey="ID_DEPARTAMENTO_ORGANIZACION" Type="TBL_DEPARTAMENTO_ORGANIZACION" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_RECURSO_COMPROMETIDO" Member="TBL_RECURSO_COMPROMETIDO">
    <Type Name="TBL_RECURSO_COMPROMETIDO">
      <Column Name="ID_RECURSO_COMPROMETIDO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOMBRE_RECURSO" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="TBL_RECURSO_COMPROMETIDO_TBL_ACCION_CORRECTIVA_RECURSO" Member="TBL_ACCION_CORRECTIVA_RECURSO" ThisKey="ID_RECURSO_COMPROMETIDO" OtherKey="ID_RECURSO_COMPROMETIDO" Type="TBL_ACCION_CORRECTIVA_RECURSO" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_SUB_ACTIVIDAD" Member="TBL_SUB_ACTIVIDAD">
    <Type Name="TBL_SUB_ACTIVIDAD">
      <Column Name="ID_SUB_ACTIVIDAD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_EVIDENCIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_PROGRAMA_ACTIVIDAD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NOMBRE_SUB_ACTIVIDAD" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TIPO_FRECUENCIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CANTIDAD_ACTIVIDADES" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="TBL_SUB_ACTIVIDAD_TBL_ACTIVIDAD_RESPONSABLE" Member="TBL_ACTIVIDAD_RESPONSABLE" ThisKey="ID_SUB_ACTIVIDAD" OtherKey="ID_SUB_ACTIVIDAD" Type="TBL_ACTIVIDAD_RESPONSABLE" />
      <Association Name="TBL_SUB_ACTIVIDAD_TBL_EVALUACION_MENSUAL" Member="TBL_EVALUACION_MENSUAL" ThisKey="ID_SUB_ACTIVIDAD" OtherKey="ID_SUB_ACTIVIDAD" Type="TBL_EVALUACION_MENSUAL" />
      <Association Name="TBL_PROGRAMA_ACTIVIDAD_TBL_SUB_ACTIVIDAD" Member="TBL_PROGRAMA_ACTIVIDAD" ThisKey="ID_PROGRAMA_ACTIVIDAD" OtherKey="ID_PROGRAMA_ACTIVIDAD" Type="TBL_PROGRAMA_ACTIVIDAD" IsForeignKey="true" />
      <Association Name="TBL_EVIDENCIA_TBL_SUB_ACTIVIDAD" Member="TBL_EVIDENCIA" ThisKey="ID_EVIDENCIA" OtherKey="ID_EVIDENCIA" Type="TBL_EVIDENCIA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_TRABAJADOR" Member="TBL_TRABAJADOR">
    <Type Name="TBL_TRABAJADOR">
      <Column Name="RUT_TRABAJADOR" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRES" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="APELLIDO_MATERNO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="APELLIDO_PATERNO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ANOS_EXPERIENCIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_TRABAJADOR" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_CARGO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_TRABAJADOR_TBL_ACTIVIDAD_TRABAJADOR_REALIZADA" Member="TBL_ACTIVIDAD_TRABAJADOR_REALIZADA" ThisKey="ID_TRABAJADOR" OtherKey="ID_TRABAJADOR" Type="TBL_ACTIVIDAD_TRABAJADOR_REALIZADA" />
      <Association Name="TBL_TRABAJADOR_TBL_EVENTO_TRABAJADOR" Member="TBL_EVENTO_TRABAJADOR" ThisKey="ID_TRABAJADOR" OtherKey="ID_TRABAJADOR" Type="TBL_EVENTO_TRABAJADOR" />
      <Association Name="TBL_CARGO_TBL_TRABAJADOR" Member="TBL_CARGO" ThisKey="ID_CARGO" OtherKey="ID_CARGO" Type="TBL_CARGO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TBL_USUARIO" Member="TBL_USUARIO">
    <Type Name="TBL_USUARIO">
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ID_USUARIO" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_EMPRESA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RUT_TRABAJADOR" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="NOMBRES" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="APELLIDO_MATERNO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="APELLIDO_PATERNO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ANOS_EXPERIENCIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TBL_USUARIO_TBL_USUARIO_GRUPO" Member="TBL_USUARIO_GRUPO" ThisKey="ID_USUARIO" OtherKey="ID_USUARIO" Type="TBL_USUARIO_GRUPO" />
      <Association Name="TBL_USUARIO_TBL_ACCION_CORRECTIVA" Member="TBL_ACCION_CORRECTIVA" ThisKey="ID_USUARIO" OtherKey="ID_USUARIO" Type="TBL_ACCION_CORRECTIVA" />
      <Association Name="TBL_USUARIO_TBL_MATRIZ" Member="TBL_MATRIZ" ThisKey="ID_USUARIO" OtherKey="ID_USUARIO" Type="TBL_MATRIZ" />
      <Association Name="TBL_EMPRESA_TBL_USUARIO" Member="TBL_EMPRESA" ThisKey="ID_EMPRESA" OtherKey="ID_EMPRESA" Type="TBL_EMPRESA" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_search_actividad_evaluada" Method="sp_search_actividad_evaluada">
    <Parameter Name="ID_ORGANIZACION" Parameter="iD_ORGANIZACION" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_DEPARTAMENTO_ORGANIZACION" Parameter="iD_DEPARTAMENTO_ORGANIZACION" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_DIVISION" Parameter="iD_DIVISION" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_AREA" Parameter="iD_AREA" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_ACTIVIDAD_GENERAL" Parameter="iD_ACTIVIDAD_GENERAL" Type="System.Int32" DbType="Int" />
    <Parameter Name="NOMBRE_ACTIVIDAD_ESPECIFICA" Parameter="nOMBRE_ACTIVIDAD_ESPECIFICA" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ID_CARGO" Parameter="iD_CARGO" Type="System.Int32" DbType="Int" />
    <Parameter Name="CONDICION" Parameter="cONDICION" Type="System.Int32" DbType="Int" />
    <Parameter Name="FECHA_INICIO" Parameter="fECHA_INICIO" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FECHA_TERMINO" Parameter="fECHA_TERMINO" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_search_actividad_evaluadaResult">
      <Column Name="ID_ACTIVIDAD_EVALUADA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_ACTIVIDAD_GENERAL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_CARGO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_DIVISION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_ACTIVIDAD_ESPECIFICA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_DEPARTAMENTO_ORGANIZACION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_PELIGRO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_AREA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VALORACION_CONSECUENCIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VALORACION_PROBABILIDAD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MEDIDA_VALORACION_CONSECUENCIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MEDIDA_VALORACION_PROBABILIDAD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FECHA_CREACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONDICION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_MATRIZ" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NOM_ACTIVIDAD_ESPECIFICA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NOMBRE_MATRIZ" Type="System.String" DbType="VarChar(336)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_matriz_by_id" Method="sp_get_matriz_by_id">
    <Parameter Name="ID_MATRIZ" Parameter="iD_MATRIZ" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_get_matriz_by_idResult">
      <Column Name="ID_MATRIZ" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NOM_ACTIVIDAD_GENERAL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NOM_ACTIVIDAD_ESPECIFICA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NOMBRE_CARGO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CONDICION" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="NOM_PELIGRO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NOMBRE_CONSECUENCIA" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CONSECUENCIA" Type="System.String" DbType="VarChar(21) NOT NULL" CanBeNull="false" />
      <Column Name="PROBABILIDAD" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="MRP" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="VALORACION_CONSECUENCIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VALORACION_PROBABILIDAD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NOM_MEDIDA_DE_CONTROL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MEDIDA_CONSECUENCIA" Type="System.String" DbType="VarChar(21) NOT NULL" CanBeNull="false" />
      <Column Name="MEDIDA_PROBABILIDAD" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="MRCC" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="MEDIDA_VALORACION_CONSECUENCIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MEDIDA_VALORACION_PROBABILIDAD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NOMBRE_ORGANIZACION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NOMBRE_DEPARTAMENTO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="NOMBRE_DIVISION" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>