/*
 * File: app/view/MatrizRiesgo.js
 * Date: Fri Sep 02 2011 11:03:55 GMT-0300 (Hora verano Sudamérica Pacífico)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('WCF_ENAP.view.MatrizRiesgo', {
    extend: 'WCF_ENAP.view.ui.MatrizRiesgo',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});