/*
 * File: app/view/MyWindow.js
 * Date: Fri Aug 19 2011 13:09:04 GMT-0400 (Hora est. Sudamérica Pacífico)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.view.MyWindow', {
    extend: 'MyApp.view.ui.MyWindow',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});