/*
 * File: designer.js
 * Date: Fri Aug 19 2011 13:16:53 GMT-0400 (Hora est. Sudamérica Pacífico)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    name: 'MyApp',

    stores: [
        'dsGrupo'
    ],

    launch: function() {
        Ext.QuickTips.init();

        var cmp1 = Ext.create('MyApp.view.MyWindow', {
            renderTo: Ext.getBody()
        });
        cmp1.show();
    }
});
