window.___jsl=window.___jsl||{};
window.___jsl.h=window.___jsl.h||'r;gc\/23980661-3686120e';
window.___jsl.l=[];
window.__GOOGLEAPIS=window.__GOOGLEAPIS||{};
window.__GOOGLEAPIS.gwidget=window.__GOOGLEAPIS.gwidget||{};
window.__GOOGLEAPIS.gwidget.superbatch=false;window.__GOOGLEAPIS.iframes=window.__GOOGLEAPIS.iframes||{};
window.__GOOGLEAPIS.iframes.plusone=window.__GOOGLEAPIS.iframes.plusone_m=window.__GOOGLEAPIS.iframes.plusone||{url:':socialhost:/u/:session_index:/_/+1/fastbutton',params:{count:'',size:'',url:''}};window.___gpq=[];
window.gapi=window.gapi||{};
window.gapi.plusone=window.gapi.plusone||(function(){
  function f(n){return function(){window.___gpq.push(n,arguments)}}
  return{go:f('go'),render:f('render')}})();
function __bsld(){var p=window.gapi.plusone=window.googleapisv0.plusone;var f;while(f=window.___gpq.shift()){
  p[f]&&p[f].apply(p,window.___gpq.shift())}
if (gadgets.config.get("gwidget")["parsetags"]!=="explicit"){gapi.plusone.go();}}
window['___jsl'] = window['___jsl'] || {};window['___jsl']['u'] = 'https:\/\/apis.google.com\/js\/plusone.js';window['___jsl']['f'] = ['googleapis.client','plusone'];window['___jsl']['ms'] = 'https://plus.google.com';(window['___jsl']['ci'] = (window['___jsl']['ci'] || [])).push({"gwidget":{"parsetags":"onload","superbatch":false},"iframes":{"sharebox":{"params":{"json":"&"},"url":":socialhost:/u/:session_index:/_/sharebox/dialog"},":socialhost:":"https://apis.google.com","plusone_m":{"url":":socialhost:/u/:session_index:/_/+1/fastbutton","params":{"count":"","size":"","url":""}},"card":{"params":{"style":"#","userid":"&"},"url":":socialhost:/u/:session_index:/_/hovercard/card"},"plusone":{"url":":socialhost:/u/:session_index:/_/+1/fastbutton","params":{"count":"","size":"","url":""}}},"googleapis.config":{"requestCache":{"enabled":true},"methods":{"chili.people.list":true,"pos.plusones.list":true,"pos.plusones.get":true,"pos.plusones.getDefaultAcl":{"cache":{"enabled":true}},"chili.people.get":true,"pos.plusones.insert":true,"chili.activities.list":true,"pos.plusones.delete":true,"chili.activities.get":true,"chili.activities.search":true,"pos.plusones.getSignupState":true},"versions":{"chili":"v1","pos":"v1"},"rpc":"/rpc","transport":{"isProxyShared":true},"sessionCache":{"enabled":true},"proxy":"https://clients6.google.com/static/proxy.html","developerKey":"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ","jsh":"r;gc/23980661-3686120e","auth":{"useInterimAuth":false}}});var jsloader=window.jsloader||{};
var gapi=window.gapi||{};
(function(){function l(b,d,a){a=j(a).join(b);e.l.length>0&&(a+=d+j(e.l).join(b));return a}function j(b){b.sort();for(var d=1;b[d];)b[d]==b[d-1]?b.splice(d,1):++d;return b}function r(b){if((m||document.readyState)!="loading")return false;if(typeof window.___gapisync!="undefined")return window.___gapisync;if(b&&(b=b.sync,typeof b!="undefined"))return b;for(var b=false,d=document.getElementsByTagName("meta"),a=0,c;c=!b&&d[a];++a)"generator"==c.getAttribute("name")&&"blogger"==c.getAttribute("content")&&
(b=true);return b}function n(b,d,a,c){if(d){if(a){if(e.c)throw"Cannot continue until a pending callback completes.";e.c=a;e.o=1}a=d;if(a.indexOf("..")>=0)a=false;else if(g==="r")a=!!a.match(s);else if(g==="m")a=!!a.match(t);else{var f=a.match(u);if((a=e.m)&&f)var f=f[2],h=f.lastIndexOf(a),a=(h==0||a.charAt(0)=="."||f.charAt(h-1)==".")&&f.length-a.length==h;else a=false}if(!a)throw"Cannot load url "+d+".";r(c)?document.write('<script src="'+d+'"><\/script>'):(c=document.createElement("script"),c.setAttribute("src",
d),document.getElementsByTagName("head")[0].appendChild(c));e.l.push.apply(e.l,b)}else a&&a()}function o(b,d){g="";e=window.___jsl=window.___jsl||{};i=window.console||window.opera&&window.opera.postError;k=b;m=d;e.l=e.l||[];var a,c=k.match(v)||k.match(w);try{a=c?decodeURIComponent(c[2]):e.h}catch(j){}a&&(a=a.split(";"),g=a.shift(),f=g==="r"?"https://ssl.gstatic.com":g==="m"?e.ms||"https://apis.google.com":a.shift(),g==="r"?(c=a.shift(),c=(c.indexOf("/")!=0?"/webclient/js/":"")+c):c=a.shift(),h=c,
p=(c=g==="d")&&a.shift()||"gcjs-3p",q=c&&a.shift()||"")}var v=/\?([^&#]*&)*jsh=([^&#]*)/,w=/#([^&]*&)*jsh=([^&]*)/,s=/^https:\/\/ssl.gstatic.com(\/([a-zA-Z0-9_\-\.,:!=]+))*\/([a-zA-Z0-9_\-\.,:!=]+)?$/,t=/^(https?:\/\/[^/]*.google.com(:[0-9]+)?)(\/([a-zA-Z0-9_\-\.,:!=]+))*\/([a-zA-Z0-9_\-\.,:!=]+)?$/,u=/^(https?:)?\/\/([^/:@]*)(:[0-9]+)?\//,e,g,f,p,q,h,i,k,m;o(document.location.href);jsloader.load=function(b,d){var a,d=d||{};if(!b||b.length==0)i&&i.warn("Cannot load empty features.");else if(g==="d")a=
b,a=(f[f.length-1]=="/"?f.substring(0,f.length-1):f)+"/"+l(":","!",a),a+=".js?container="+p+"&c=2&jsload=0",h&&(a+="&r="+h),q=="d"&&(a+="&debug=1");else if(g==="r"||g==="f")a=f+(h.indexOf("/")!=0?"/":"")+h+"/"+l("__","--",b)+".js";else if(g==="m"||g==="n"){var c=b;(a=!!d.nodep)||(c=j(c));c=c.join(",").replace(/\.|-/g,"_","g");c=f+h.replace("__features__",c);a&&(c=c.replace("/d=1/","/d=0/"));a=c}else c="Cannot respond for features ["+b.join(",")+"].",i&&i.warn(c);typeof d==="function"?n(b,a,d):((e.cu=
e.cu||[]).push(d.config),c=d.callback,n(b,a,c,d))};jsloader.reinitialize_=function(b,d){o(b,d)}})();
gapi.load=function(a,b){jsloader.load(a.split(":"),b)};
(window.gapi=window.gapi||{}).load=gapi.load;
gapi.load('googleapis.client:plusone', {'callback': window['__bsld']  });